In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# 数据处理

In [2]:
# 将数据集赋值给cancer变量
cancer = load_breast_cancer()
print('breast_cancer数据集的长度为：', len(cancer))
print('breast_cancer数据集的类型为：', type(cancer))

breast_cancer数据集的长度为： 8
breast_cancer数据集的类型为： <class 'sklearn.utils.Bunch'>


In [3]:
# 获取cancer数据集的数据
cancer_data = cancer['data']
print('breast_cancer数据集的数据为：\n', cancer_data)

breast_cancer数据集的数据为：
 [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [4]:
# 取出cancer数据集的标签
cancer_target = cancer['target']
print('breast_cancer数据集的标签为：\n', cancer_target)

breast_cancer数据集的标签为：
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1

In [5]:
# 取出cancer数据集的特征名
cancer_names = cancer['feature_names']
print('breast_cancer数据集的特征名为：\n', cancer_names)

breast_cancer数据集的特征名为：
 ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [6]:
# 取出cancer数据集的描述信息
cancer_desc = cancer['DESCR']
print('breast_cancer数据集的描述信息为：\n',cancer_desc)

breast_cancer数据集的描述信息为：
 .. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For insta

In [7]:
# 数据集的相撞
print('breast_cancer数据集数据的形状为：', cancer_data.shape)
print('breast_cancer数据集标签的形状为：', cancer_target.shape)

breast_cancer数据集数据的形状为： (569, 30)
breast_cancer数据集标签的形状为： (569,)


# 划分数据集

In [8]:
# 训练集/测试集划分
cancer_data_train, cancer_data_test, cancer_target_train, cancer_target_test = train_test_split(cancer_data, cancer_target, test_size=0.2, random_state=42)
print('breast_cancer训练集数据的形状为：', cancer_data_train.shape)
print('breast_cancer训练集标签的形状为：', cancer_target_train.shape)
print('breast_cancer测试集数据的形状为：', cancer_data_test.shape)
print('breast_cancer测试集标签的形状为：', cancer_target_test.shape)

breast_cancer训练集数据的形状为： (455, 30)
breast_cancer训练集标签的形状为： (455,)
breast_cancer测试集数据的形状为： (114, 30)
breast_cancer测试集标签的形状为： (114,)


# 离差标准化

In [10]:
# 生成规则
Scaler = MinMaxScaler().fit(cancer_data_train)
# 将规则应用于训练集
cancer_trainScaler = Scaler.transform(cancer_data_train) 
# 将规则应用于测试集
cancer_testScaler = Scaler.transform(cancer_data_test)
print('离差标准化前breast_cancer训练集数据的最小值为：', np.min(cancer_data_train))
print('离差标准化后breast_cancer训练集数据的最小值为：', np.min(cancer_trainScaler))
print('离差标准化前breast_cancer训练集数据的最大值为：', np.max(cancer_data_train))
print('离差标准化后breast_cancer训练集数据的最大值为：', np.max(cancer_trainScaler))
print('离差标准化前breast_cancer测试集数据的最小值为：', np.min(cancer_data_test))
print('离差标准化后breast_cancer测试集数据的最小值为：', np.min(cancer_testScaler))
print('离差标准化前breast_cancer测试集数据的最大值为：', np.max(cancer_data_test))
print('离差标准化后breast_cancer测试集数据的最大值为：', np.max(cancer_testScaler))

离差标准化前breast_cancer训练集数据的最小值为： 0.0
离差标准化后breast_cancer训练集数据的最小值为： 0.0
离差标准化前breast_cancer训练集数据的最大值为： 4254.0
离差标准化后breast_cancer训练集数据的最大值为： 1.0000000000000002
离差标准化前breast_cancer测试集数据的最小值为： 0.0
离差标准化后breast_cancer测试集数据的最小值为： -0.057127602776294695
离差标准化前breast_cancer测试集数据的最大值为： 3432.0
离差标准化后breast_cancer测试集数据的最大值为： 1.3264399566986453


In [11]:
# 生成规则
pca_model = PCA(n_components=10).fit(cancer_trainScaler)
# 将规则应用于训练集
cancer_trainPca = pca_model.transform(cancer_trainScaler)
# 将规则应用于测试集
cancer_testPca = pca_model.transform(cancer_testScaler)
print('PCA降维前breast_cancer训练集数据的形状为：', cancer_trainScaler.shape)
print('PCA降维后breast_cancer训练集数据的形状为：', cancer_trainPca.shape)
print('PCA降维前breast_cancer测试集数据的形状为：', cancer_testScaler.shape)
print('PCA降维后breast_cancer测试集数据的形状为：', cancer_testPca.shape)

PCA降维前breast_cancer训练集数据的形状为： (455, 30)
PCA降维后breast_cancer训练集数据的形状为： (455, 10)
PCA降维前breast_cancer测试集数据的形状为： (114, 30)
PCA降维后breast_cancer测试集数据的形状为： (114, 10)
